# Assignment 2 - NumPy

Q1. Create an array of 10 fives


In [19]:
import numpy as np
arr = np.zeros(10)
arr+5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

Q2. Create an array of the integers from 10 to 50

In [20]:
import numpy as np
arr = np.arange(10,51)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

Q3. Create an array of all the even integers from 10 to 50

In [21]:
import numpy as np
arr = np.arange(10,51,2)
arr

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

Q4. Create a 3x3 matrix with values ranging from 0 to 8


In [22]:
import numpy as np
arr=np.arange(0,9)
arr=arr.reshape(3,3)
arr


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Q5. Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [23]:
import numpy as np
arr=np.random.normal(0,100,25)
arr

array([ -80.17636029,  -31.57546258,  -29.99160371,  -14.89471415,
         30.18629833,   28.80182394,    3.78667865,   50.45810715,
        -46.18977932, -145.87071893,   63.75657833,  -99.32287939,
         53.88289552,   51.25564647,  -15.76724737, -112.61023833,
         22.74603842,   53.54873439, -112.18250651,  102.11194898,
        175.53609519,  -44.36795531,   59.99124586,  -78.59968765,
        162.2413895 ])

Q6. Create the following array:

array([0. , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ,
 0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21,
 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32,
 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43,
 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54,
 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65,
 0.66, 0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76,
 0.77, 0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87,
 0.88, 0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98,
 0.99, 1. ])

In [24]:
import numpy as np
arr=np.arange(0,1.01,0.01)
arr

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ,
       0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21,
       0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32,
       0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43,
       0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54,
       0.55, 0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65,
       0.66, 0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76,
       0.77, 0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87,
       0.88, 0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98,
       0.99, 1.  ])

Q7. Create an array of 20 linearly spaced points between 0 and 1


In [25]:
import numpy as np
arr=np.linspace(0,1,20)
arr

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

Q8. Generate the following matrix :

array([[ 1, 2, 3, 4, 5],
 [ 6, 7, 8, 9, 10],
 [11, 12, 13, 14, 15],
 [16, 17, 18, 19, 20],
 [21, 22, 23, 24, 25]])

and extract the following using the indexing and slicing :

array([[12, 13, 14, 15],
 [17, 18, 19, 20],
 [22, 23, 24, 25]])

array([[ 2],
 [ 7],
 [12]])

Get the sum of all the values in mat

Get the sum of all the rows and columns in mat


In [26]:
import numpy as np
arr=np.arange(1,26)
mat=arr.reshape(5,5)
print("mat = \n",mat)
print("\n")

arr1=mat[2:,1:]
print("arr1 = \n",arr1)
print("\n")

arr2=mat[0:3,1]
print("arr2 = \n",arr2.reshape(3,1))
print("\n")

print("Sum of all values in matrix : ",np.sum(mat))
print("\n")
print("Sum of values along row : ",np.sum(mat,axis=1).reshape(5,1))
print("\n")
print("Sum of values along column : ",np.sum(mat,axis=0).reshape(1,5))

mat = 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


arr1 = 
 [[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


arr2 = 
 [[ 2]
 [ 7]
 [12]]


Sum of all values in matrix :  325


Sum of values along row :  [[ 15]
 [ 40]
 [ 65]
 [ 90]
 [115]]


Sum of values along column :  [[55 60 65 70 75]]
